sudo: required
langauage: generic
services: 
  - docker

before_install:
  - docker build -t surajoraon/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true surajoraon/docker-react npm run test -- --coverage 