sudo: required
langauage: generic
services: 
  - docker

before_install:
  - docker build -t surajoraon/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true surajoraon/docker-react npm run test -- --coverage 

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-947002134052"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"